AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  sam-app

  Sample SAM Template for sam-app

Globals:
  Function:
    Timeout: 10

Resources:
  HelloWorldFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: app/
      Handler: app.handler
      Runtime: nodejs20.x
      Architectures:
        - x86_64
      Events:
        Express:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /{proxy+}
            Method: any

Outputs:
  ExpressApi:
    Description: 'API Gateway endpoint URL for Prod stage for Express function'
    Value: !Sub 'https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/'
  ExpressFunction:
    Description: 'Express Lambda Function ARN'
    Value: !GetAtt ExpressFunction.Arn
  ExpressFunctionIamRole:
    Description: 'Implicit IAM Role created for Express function'
    Value: !GetAtt ExpressFunctionRole.Arn
